### PR TITLE
enable center align for dpdw content + fix alignment

### PR DESCRIPTION
**Pull request by dani69654**
closes https://github.com/web3ui/web3uikit/issues/951

https://www.loom.com/share/8cbcb798db7f4156b998db424383f99e

### CODE REVIEW

**Review by AbhinavMV — COMMENTED** [review]
Hey bro nice work 
Just have some questions
1. When the option with icon (eg: <icon> testnet) is selected, this is how it is displayed. Is this how it should be displayed? 🤔  
image

2. From the design in the issue I can see that even the dropdown arrow is centered. but not in the story. Maybe design was not updated not sure. 

If these two things are ok and no changes are needed to PR please go ahead and merge this @dani69654 🙌🏻

**Comment by dani69654** [comment]
Hey @AbhinavMV , thanks for reviewing:

> When the option with icon (eg: testnet) is selected, this is how it is displayed. Is this how it should be displayed?
This is how it works now, not sure if it is correct, I did not work on that in this MR. If we don't like it we can surely change its behaviour.

> From the design in the issue I can see that even the dropdown arrow is centered. but not in the story. Maybe design was not updated not sure.

You are right, I missed that. On it, good catch

**Comment by dani69654** [comment]
Screenshot 2022-12-15 at 10 01 39

**Review by AbhinavMV — APPROVED** [review]
LGTM 🚀

**Pull request merged**
