### PR TITLE
fix social icons to make them viewable

### PR DESCRIPTION
**Pull request by CryptoLover705**
Social icons `Reddit`, `Telegram`, `Twitter` & `Github` have been resized to make them viewable

### CODE REVIEW

**Comment by BillyG83** [comment]
hey sorry @CryptoLover705 i made this fix myself and forgot to push the branch. Also my bad that i did not check it better, its been very busy. And again TY for following up with the fix. I'll leave this open and check if maybe you found better icons than me

**Comment by CryptoLover705** [comment]
Hey @BillyG83 it's all good, It was my fault for not checking the sizes of the SVG's in the first place

**Comment by locothedev** [comment]
@CryptoLover705 resolve conflict please

**Comment by CryptoLover705** [comment]
Conflicts have been resolved @locothedev

**Comment by BillyG83** [comment]
i'm going to close this for now as i have added the fix. TY

**Pull request closed without merging**
