### PR TITLE
fix: oneline textarea bug

### LINKED ISSUE #452: [Bug]: Code Area Component
# Issue: 
Code area text is rendering in a single line even though extra lines are being added.
# Expected:
Text should render in mulitple lines.

This can be replicated in mozilla firefox. (confirmed by @locothedev as well)
@Y0moo 

https://user-images.githubusercontent.com/35369843/163420643-819442d3-bfa9-4d28-82a1-c75c24ddb65a.mp4

** Placed the cursor somewhere and pressed enter key several times

### PR DESCRIPTION
**Pull request by Y0moo**
Works correctly on firefox browser now

closes #452

image

### CODE REVIEW

**Comment by Y0moo** [comment]
@AbhinavMV could you check how this one works now for you?

**Review by AbhinavMV — APPROVED** [review]
Awesome its working in mozilla as well now.  🚀

**Comment by AbhinavMV** [comment]
Btw there are no tests for this component.
Should we add one basic test in this PR only or create a new issue? @Y0moo

**Comment by BillyG83** [comment]
no tests? wow how did that slip by, yeah please add them @AbhinavMV TY

**Comment by AbhinavMV** [comment]
Have added some basic tests for all stories.
And also added this component in readme file.

**Pull request merged**
