### PR TITLE
feat: add sorting columns for table

### PR DESCRIPTION
**Pull request by AbhinavMV**
---
name: 'Table Component'
about: Sorting columns
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/web3ui/web3uikit/blob/master/CONTRIBUTE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #610 

### Solution Description

Added a prop that would take boolean array input. True if column is sortable else false.
On clicking on appropriate table header the table would be sorted.
Please checkout Table-> Sync Table example story

### CODE REVIEW

**Comment by osamajandali** [comment]
I liked the approach so much! Great job @AbhinavMV 

My only concern is that this client side sorting only and this approach won’t work for server side sorting, have you thought about this or you indented to make it client side sorting only?

let me know if you need more clarification of what I said.

**Comment by AbhinavMV** [comment]
Thanks @osamajandali 

Hmm i was only going for client side sorting. 
Usually for tables sorting is done when user clicks on headers, have not seen many usecases for server side sorting here.

Let me know if you think it would be a helpful feature, will be happy to learn and implement it 💪🏻

**Comment by osamajandali** [comment]
Thanks for explaining @AbhinavMV 
I think we can go with this one at the moment and add the server side later.

Just FYI why I think about server side because of those scenarios: 

- Imagine a table of 1000 or maybe 10,000 columns which is a lot of data, so then for sure the request won't get you all of those data at one request, there should be a way for lazy loading or a pagination which on every page of the table you request the next 10/20 records..so then you don't have all the 10k data where you can perform the sorting on them.
- The second scenario is that, during the integration the api maybe have a pagination on it which lead you then to call the request multiple times to get all the data and then sort them on the client side end.

But again for the most cases client sorting works just fine.

Maybe @BillyG83 can give us more input on this matter

**Comment by AbhinavMV** [comment]
Ohh got it 🙌🏻
Thanks for explaining 
Yes we can add server side later on. 🤝

**Review by osamajandali — APPROVED** [review]
Let's gooo 🚀

**Pull request merged**
