### PR TITLE
Add base Tabs component

### PR DESCRIPTION
**Pull request by poverenje**

### CODE REVIEW

**Comment by locothedev** [comment]
Thank you for contributing 🥇  . 

Here are some suggestions:

- create a folder for each sub-component. `Tabs/TabList/TabList.tsx` and `Tabs/TabPanel/TabsPanel.tsx` and so on 
- same goes for hooks and context, try to create a more clear folder structure
- remove types/interfaces to types.ts for each component
- make comments for each type in interfaces for a smooth dev experience
- more tests :P

All in all the components work perfectly fine. If you make these changes we may build on top of this and apply top design to it. 

again.. THANK YOU

**Comment by poverenje** [comment]
This is Google translate, my level is A2-B1. I can't write complex texts.

I couldn't find a style guide and don't know what styles are needed. Haven't written any tests yet :) I'm working on it. Sorry for the early pull request, this is my first time.

Have a good day))

**Comment by BillyG83** [comment]
Greetings @poverenje Thank you so much for contributing. The message was very clear. Google translate is working very well.

This is a great start and we are very happy with your progress. If you have any questions you can ask us here. If you need help to style, I know CSS can be tricky, we can style it for you at the end.

Thank you, keep up the great work my friend =]

**Comment by poverenje** [comment]
I think I'm done. If you have any suggestions, I would be happy to take them. Unfortunately, my vacation is ending and I won't have much time for this. I hope that you will find my contribution useful and that you can find some use for it. I'm sure I need to improve the styles and testing. I will try to find time for that in the future. 

Best of luck))

**Comment by locothedev** [comment]
> I think I'm done. If you have any suggestions, I would be happy to take them. Unfortunately, my vacation is ending and I won't have much time for this. I hope that you will find my contribution useful and that you can find some use for it. I'm sure I need to improve the styles and testing. I will try to find time for that in the future.
> 
> Best of luck))

You have been a huge help and your Tabs component is indeed very useful and actually very needed! Thank you very much! We hope that you will contribute in the future! Kak diela 🥇

**Pull request closed without merging**
