### PR TITLE
fix: change name of Information component

### PR DESCRIPTION
**Pull request by SidharthK2**
---
name: 'Pull request'
about: A new pull request
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/web3ui/web3uikit/blob/master/CONTRIBUTE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Information component name incorrectly displayed on Storybook

### Solution Description

Changed the component name from `<Info/>` to `<Information/>`

### CODE REVIEW

**Comment by BillyG83** [comment]
nice @SidharthK2 can you run `pnpm changset` and select no major and no minor update then push the file it creates with a crazy name please?

**Review by BillyG83 — APPROVED** [review]
LGTM! can you add the changeset file or ping me if its confusing. I can do it for you 💚

**Review by AbhinavMV — APPROVED** [review]
Awesome job @SidharthK2  
LGTM 🚀

**Comment by BillyG83** [comment]
welcome to the web3uiKit fam @SidharthK2

**Pull request merged**
