### PR TITLE
Feat:blocknumber addedcomp

### PR DESCRIPTION
**Pull request by 3scava1i3r**
---
name: 'feat:Added BlockNumber'
about: Pr for issue #695 
---

### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [x] My code is conform the [code style](https://github.com/web3ui/web3uikit/blob/master/CONTRIBUTE.md)
- [x] I have made corresponding changes to the documentation
- [x] I have updated Typescript definitions when needed

### Issue Description

Related issue: #695 

### Solution Description

It takes no props just a provider should be available for it to from moralis
final screenshot
dd

### CODE REVIEW

**Comment by AbhinavMV** [comment]
This PR also has ENS Avatar changes 
Could you please remove those 🙌🏻

**Comment by 3scava1i3r** [comment]
@AbhinavMV  removed the ENSAvatar changes and added prettier to configure my code 
thank you for the help🥂

**Comment by AbhinavMV** [comment]
Looks nice
Could you remove unnecessary console logs 🙌🏻 
How about we use Typography comp to display block number, Devs can then select which type of html tag to use h1,h2.... and also give more styling options.
What do you think? 🤔

**Comment by 3scava1i3r** [comment]
surely i would remove all the unnecessary console.logs, I don't have any idea on typography comp.Would you mind giving a link or something for me to look at

**Comment by AbhinavMV** [comment]
@BillyG83 what do you think about returning typography comp instead of span html tag?

https://web3ui.github.io/web3uikit/?path=/story/4-ui-typography--heading-1
@3scava1i3r  You can check here about typography component,

**Comment by 3scava1i3r** [comment]
I understand this now,we can add the same in native balance as well

**Comment by BillyG83** [comment]
@AbhinavMV please review and merge if you are happy

**Comment by AbhinavMV** [comment]
Great job here @3scava1i3r 

This looks good. 🚀 
Could you remove console logs and unused code? 
And if you can please also add Typography component (I can add this later if you are having any trouble 🙌🏻 )

**Comment by 3scava1i3r** [comment]
I can start the work on typography also will add the same for the native balance one what do you think @AbhinavMV

**Comment by AbhinavMV** [comment]
Sure go ahead @3scava1i3r 
Please note that native balance is used in connect button comp, so please do check there if it breaks there.
If it does leave it for now 🙌🏻

**Comment by AbhinavMV** [comment]
TY @3scava1i3r, Nice job 🔥 🚀

**Pull request merged**
