### PR TITLE
feat: custom type for stepper title and content

### PR DESCRIPTION
**Pull request by dani69654**
Enabled ReactNode type for `Stepper` title and content. <br>
This is required by designed here:

image

### CODE REVIEW

**Review by BillyG83 — CHANGES_REQUESTED** [review]
could it now be easier to pass the string to Typography on line 82 of Stepper and remove the H2Styled all together?

**Comment by dani69654** [comment]
@BillyG83 Using typography for both title and content.

**Review by BillyG83 — APPROVED** [review]
nice @dani69654!!

**Comment by BillyG83** [comment]
can you resolve the conflict please @dani69654 🙏

**Comment by dani69654** [comment]
@BillyG83 Conflicts have been fixed

**Pull request merged**
