### PR TITLE
558 responsive button on todo component

### PR DESCRIPTION
**Pull request by akinolu52**
fix for small device

Screenshot 2022-05-05 at 09 18 49

### CODE REVIEW

**Review by BillyG83 — CHANGES_REQUESTED** [review]
hey @akinolu52 can you check the commits? It looks like you reformatted a bunch of files with prettier or something. Can you just commit the code you want on this review? It might be a local prettier issue for you, we can test this later if you like

**Comment by akinolu52** [comment]
okay

**Comment by akinolu52** [comment]
@BillyG83 pls re-check

**Comment by AbhinavMV** [comment]
Great Job. LGTM 🚀

**Review by AbhinavMV — APPROVED** [review]

**Review by BillyG83 — APPROVED** [review]
thats damn fine work dude, damn fine =]

**Pull request merged**
